[package]
name = "commitaura"
version = "1.0.0"
edition = "2021"

[dependencies]
openai_api_rust = "0.1.9"
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"
console = "0.15"
dialoguer = "0.11.0"
indicatif = "0.17"
log = "0.4"
env_logger = "0.11.5"
dotenv = "0.15"
thiserror = "1.0"
