[package]
name = "commitaura"
version = "1.0.0"
edition = "2021"

[dependencies]
anthropic = "0.0.8"
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"
dotenv = "0.15"
env_logger = "0.11.5"
log = "0.4"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
openai_api_rust = "0.1.9"
